package openvpn

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// writeServerConfig renders and writes server.conf from o.ovCfg. Simplified
// from vpn-ui's buildServerConfig: one transport, no client-config-dir IP
// pinning, no per-account device caps (see package doc — these are "next").
//
// Auth: username/password via a callback into this same node binary
// (auth-user-pass-verify ... via-file), same mechanism vpn-ui itself uses.
func (o *OpenVpn) writeServerConfig() error {
	cfg := o.ovCfg
	_, netAddr, mask, err := serverSubnetAddr(cfg.Subnet)
	if err != nil {
		return err
	}

	selfExe, err := selfExecutable()
	if err != nil {
		return fmt.Errorf("resolve own executable path: %w", err)
	}

	caPath, certPath, keyPath, tcPath := certPaths(o.dir)

	var b strings.Builder
	fmt.Fprintf(&b, "# Auto-generated by pasarguard-node (custom openvpn backend)\n")
	fmt.Fprintf(&b, "port %d\n", cfg.Port)
	fmt.Fprintf(&b, "proto %s\n", cfg.serverProto())
	fmt.Fprintf(&b, "dev %s\n", cfg.Device)
	b.WriteString("dev-type tun\n")
	b.WriteString("topology subnet\n")
	fmt.Fprintf(&b, "server %s %s\n", netAddr.String(), mask.String())
	b.WriteString("push \"redirect-gateway def1 bypass-dhcp\"\n")
	fmt.Fprintf(&b, "push \"dhcp-option DNS %s\"\n", cfg.Dns1)
	fmt.Fprintf(&b, "push \"dhcp-option DNS %s\"\n", cfg.Dns2)
	fmt.Fprintf(&b, "tun-mtu %d\n", cfg.Mtu)

	fmt.Fprintf(&b, "ca %s\n", caPath)
	fmt.Fprintf(&b, "cert %s\n", certPath)
	fmt.Fprintf(&b, "key %s\n", keyPath)
	fmt.Fprintf(&b, "tls-crypt %s\n", tcPath)
	b.WriteString("dh none\n")

	b.WriteString("data-ciphers AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305\n")
	b.WriteString("cipher AES-256-GCM\n")
	b.WriteString("auth SHA256\n")

	// No client certs — every connecting client authenticates by username/
	// password, verified against dir/users.json via a hook into ourselves.
	b.WriteString("verify-client-cert none\n")
	b.WriteString("username-as-common-name\n")
	b.WriteString("script-security 3\n")
	fmt.Fprintf(&b, "auth-user-pass-verify \"%s openvpn-auth %s\" via-file\n", selfExe, o.dir)

	b.WriteString("keepalive 10 120\n")
	b.WriteString("persist-key\n")
	b.WriteString("persist-tun\n")
	fmt.Fprintf(&b, "status %s 5\n", o.statusPath())
	b.WriteString("status-version 3\n")
	fmt.Fprintf(&b, "management %s unix\n", o.mgmtSockPath())
	b.WriteString("verb 3\n")
	b.WriteString("explicit-exit-notify 1\n")

	return os.WriteFile(o.confPath(), []byte(b.String()), 0644)
}

// selfExecutable resolves the running node binary's real path, the same way
// vpn-ui's OpenVpnService.binaryPath does for its own hooks.
func selfExecutable() (string, error) {
	exe, err := os.Executable()
	if err != nil {
		return "", err
	}
	if resolved, err := filepath.EvalSymlinks(exe); err == nil {
		return resolved, nil
	}
	return exe, nil
}
